version: "3.7"
services: 
    web:
        build:
            context: ./api
        restart: always
        ports:
            - 5000:5000
        depends_on: 
            - db
        networks:
            - flask_network
    db:
        image: postgres:13
        restart: always
        ports:
            - 5432:5432
        networks:
            - flask_network
        environment: 
            - POSTGRES_USER=flask_user
            - POSTGRES_PASSWORD=pass123word
            - POSTGRES_DB=flask_application
        volumes: 
            - postgres_data:/var/lib/postgresql/data


networks:
    flask_network:

volumes: 
    postgres_data: