version: "3.7"
services: 
    api:
        build:
            context: ./api
        restart: always
        ports:
            - 5000:5000
        networks:
            - brawlstars-app
    app:
        build:
            context: ./app
        volumes:
            - react_build:/app/build
    proxy:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
            - react_build:/var/www/react
        depends_on:
            - api
            - app
        networks:
            - brawlstars-app

networks:
    brawlstars-app:
        driver: bridge
volumes: 
    react_build: